### ISSUE TITLE
Clarification on modifications

### ISSUE THREAD

**Issue by yruen** [SeymourSchlong/splashtags#2]
I think your website is really neat, is there any rules regarding helping contribute to the project? As it doesn't contain any sort of license, legally people aren't allowed to modify the source code (no license = rights are reserved).

**Comment by SeymourSchlong** [comment]
oh my bad! i mustve forgotten to add it when creating... im not too familiar with the licenses, but i believe the GNU general public license would be the best one here
anyone is free to modify the source code 👍
